name: React App Pipeline

trigger:
  branches:
    include:
    - public-main
  paths:
    include:
    - SinglePageApp/ClientApp/*

pr: none

variables:
  sourceId: sourceCode_$(Build.BuildId)

pool:
  vmImage: 'ubuntu-18.04'

stages:
  - stage: Checkout
    displayName: 'Checkout out source'
    jobs:
    - job: 'Checkout'
      steps:
        - checkout: self

        - publish: $(Build.SourcesDirectory)
          displayName: 'Stash source'
          artifact: $(sourceId)

        - publish: $(Build.SourcesDirectory)/devops
          displayName: 'Stash devops'
          artifact: devops_$(sourceId)

  - stage: QualityGates
    displayName: 'Quality Gates'
    jobs: 
    - job: Build
      displayName: 'Build'
      steps:
      - checkout: none

      - task: DownloadPipelineArtifact@2
        displayName: 'Unstash source'
        inputs:
          artifact: $(sourceId)
          path: $(Build.SourcesDirectory)

      - task: DownloadPipelineArtifact@2
        displayName: 'Unstash devops'
        inputs:
          artifact: devops_$(sourceId)
          path: $(Build.SourcesDirectory)/devops

      - bash: |
          ls
        displayName: 'debug'



