pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                sh '''
                cd ./SinglePageApp/ClientApp/
                npm run i
                npm run build 
                npm run test
                '''
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}